ureca-capstone4/idle-server

src/main/java/com/ureca/idle/application/DummyRecommendUseCase.java
src/main/java/com/ureca/idle/application/RedisDummyRecommendService.java
src/main/java/com/ureca/idle/batch/DummyBatch.java
src/main/java/com/ureca/idle/common/language/IdleJavaUtil.java
src/main/java/com/ureca/idle/common/logging/IdleLogging.java
src/main/java/com/ureca/idle/domain/dummy/entity/Dummy.java
src/main/java/com/ureca/idle/domain/dummy/manager/DummyManager.java
src/main/java/com/ureca/idle/domain/dummy/persistence/DummyRepository.java
src/main/java/com/ureca/idle/inbound/api/DummyRecommendController.java
src/main/java/com/ureca/idle/inbound/health/HealthController.java
src/main/java/com/ureca/idle/outbound/ai/AiOperation.java
src/main/java/com/ureca/idle/outbound/circuitbreaker/CircuitBreakerConfig.java
src/main/java/com/ureca/idle/outbound/redis/RedisConfig.java
src/main/java/com/ureca/idle/outbound/redis/RedisOperation.java

pull request template will be applied soon...

Initialize package structure

---

src/main/java/com/ureca/idle/idlejpa/book/Book.java
src/main/java/com/ureca/idle/idlejpa/booksdetail/BooksDetail.java
src/main/java/com/ureca/idle/idlejpa/kid/Kid.java
src/main/java/com/ureca/idle/idlejpa/kidspersonality/KidsPersonality.java
src/main/java/com/ureca/idle/idlejpa/preferences/Hobulho.java
src/main/java/com/ureca/idle/idlejpa/preferences/Preferences.java

> ## 📝 관련 이슈
---
- [resolves]: #[JPA 모듈 개발](https://trello.com/c/ROeYqM4k/24-id-24-jpa-%EB%AA%A8%EB%93%88-%EA%B0%9C%EB%B0%9C) #ID-24
> ## 💻 작업 내용
- 엔티티 추가
---
> ## 🙇 특이 사항
- 추후 선착순 응모 이벤트 관련 엔티티 추가 필요
---
- 꼼꼼히 봐주시면 감사드리겠습니다.
---

[ID-24] JPA 모듈 개발

---

.github/workflows/idle.yml
build.gradle

> ## 📝 관련 이슈
---
[resolves]: #[ci 세팅](https://trello.com/c/pVbLkt3b/11-id-11-github-ci-%EC%84%A4%EA%B3%84) #ID-11
> ## 💻 작업 내용
- Ci 세팅 완료했습니단~ spotless이용했습니다.
- spotless라는 거를 사용해서 코드 컨밴션을 체크하도록 했구요 자세한거는 링크 참조한거 보시면 될거 같아요~~
- 앞으로 커밋하기전에 터미널에서 **./gradlew spotlessCheck** 한번 하고 올려주시면 ci에서 실패안하고 다시 고쳐서 올리는 일 없을거 같습니단~
- 만약 체크해서 빌드 실패가 뜬다면 **./gradlew spotlessApply** 명령어 쳐서 컨벤션 적용시켜 주세요~
---
> ## 🙇 특이 사항
- 밑에는 참조 링크 입니다~
https://github.com/diffplug/spotless
https://velog.io/@bum12ark/Spotless-%EC%BD%94%EB%93%9C-%ED%8F%AC%EB%A7%B7%ED%8C%85
https://velog.io/@cekim/briefing-spotless
---

[ID-11] CI 세팅

---

src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/KidManagingService.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/KidManagingUseCase.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/dto/AddKidReq.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/dto/GetKidsDetailResp.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/dto/GetKidsDetailsResp.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/dto/GetKidsPersonalityResp.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/dto/GetKidsProfileResp.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/dto/GetKidsProfilesResp.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/dto/GetMyKidsProfileResp.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/common/exception/KidNotFoundException.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/kid/KidManager.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/mapper/KidDtoMapper.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/user/UserManager.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/kid/KidRepository.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentaion/kid/KidManagingController.java
src/main/java/com/ureca/idle/idlejpa/book/Book.java
src/main/java/com/ureca/idle/idlejpa/booksdetail/BooksDetail.java
src/main/java/com/ureca/idle/idlejpa/kid/Gender.java
src/main/java/com/ureca/idle/idlejpa/kid/Kid.java

> ## 📝 관련 이슈
---
- [resolves]: [자녀 프로필 생성 및 관리 기능](https://trello.com/c/t0fnB0ay/14-id-14-%EC%9E%90%EB%85%80-%ED%94%84%EB%A1%9C%ED%95%84-%EC%83%9D%EC%84%B1-%EB%B0%8F-%EA%B4%80%EB%A6%AC-%EA%B8%B0%EB%8A%A5)
> ## 💻 작업 내용
- 자녀 프로필과 성향을 한번에 가져오는 getKidsDetail 구현
- 이외 각종 자잘한 네이밍, 자녀 성별 추가
---
> ## 🙇 특이 사항
- 
---
- 
---

[ID-14] 자녀 프로필 생성 및 관리 기능

---

src/main/java/com/ureca/idle/idlejpa/submission/CurrentRoundSubmission.java
src/main/java/com/ureca/idle/idlejpa/submission/PreviousRoundSubmission.java

> ## 📝 관련 이슈
---
- [resolves]: [ID - 36 응모 엔티티 생성](https://trello.com/c/ThbSMkrv/36-id-36-%EC%9D%91%EB%AA%A8-%EC%97%94%ED%8B%B0%ED%8B%B0-%EC%83%9D%EC%84%B1)
> ## 💻 작업 내용
- 엔티티 클래스 생성
---
> ## 🙇 특이 사항
- ERD Cloud 확인
---
- 
---

[ID-36] 응모 엔티티 생성

---

src/main/java/com/ureca/idle/idlejpa/kidspersonality/KidsPersonalityChangeHistory.java
src/main/java/com/ureca/idle/idlejpa/kidspersonality/KidsPersonalityDeleteHistory.java

> ## 📝 관련 이슈
---
- [resolves]: [ID-37 자녀 성향 히스토리 테이블 생성](https://trello.com/c/YN1LsE0D/37-id-37-%EC%9E%90%EB%85%80-%EC%84%B1%ED%96%A5-%ED%9E%88%EC%8A%A4%ED%86%A0%EB%A6%AC-%ED%85%8C%EC%9D%B4%EB%B8%94-%EC%83%9D%EC%84%B1)
> ## 💻 작업 내용
- 자녀 성향 히스토리 테이블 생성
---
> ## 🙇 특이 사항
- 
---
- 
---

[ID-37] 자녀 성향 히스토리 테이블 생성

---

src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/BookManagingService.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/BookManagingUseCase.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/GetBookProfileResp.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/GetRecommendedBooksResp.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/book/BookManager.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/mapper/BookDtoMapper.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/book/BookRepository.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/controller/book/BookManagingController.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/controller/personality/PersonalityController.java
src/test/java/com/ureca/idle/idleapi/idleoriginapi/implementation/BookManagerTest.java

> ## 📝 관련 이슈
---
- [resolves]: [ID-40 추천 알고리즘 구현](https://trello.com/c/XOylNjwV/40-id-40-%EC%B6%94%EC%B2%9C-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B5%AC%ED%98%84)
> ## 💻 작업 내용
- 책 추천 로직 추가 및 관련된 코드 추가
---
> ## 🙇 특이 사항
- 저번에 패키지 오타 수정이 반영이 안 된 것 같아 이번에 수정했습니다
---
- 포스트맨 돌려보셔도 되고, 필요한 쿼리는 노션에 제 페이지에 올려두겠습니다.
---

[ID-40] 추천 알고리즘 구현

---

src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/KidManagingService.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/KidManagingUseCase.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/dto/UpdateKidPersonalityReq.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/dto/UpdateKidPersonalityResp.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/personality/PersonalityManagingService.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/personality/PersonalityManagingUseCase.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/kid/KidManager.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/mapper/KidDtoMapper.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/kid/KidRepository.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/kidPersonality/KidsPersonalityRepository.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/controller/kid/KidManagingController.java
src/main/java/com/ureca/idle/idlejpa/kidspersonality/KidsPersonality.java

> ## 📝 관련 이슈
---
- [resolves]: [[ID-25 MBTI 성향 기능 구현하기](https://trello.com/c/MWBIhvL4/25-id-25-mbti-%EC%84%B1%ED%96%A5-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)
> ## 💻 작업 내용
- 자녀가 진행한 테스트 결과가 반영되는 기능을 구현했습니다.
---
> ## 🙇 특이 사항
- 자녀 생성시, Default 성향이 생성된다는 전제하에 개발되었습니다. Postman으로 테스트시 임시로 Kids의 kids_personality를 생성해 연결한 뒤에 진행했습니다.
---
- 수정해야하거나 별로인 부분 정말 꼭 피드백 주시면 수정하겠습니다!
---

[ID-25] 성향 업데이트 기능 구현

---

src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/BookManagingService.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/AddBookReq.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/kid/KidManagingService.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/personality/PersonalityManagingService.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/book/BookManager.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/kid/KidManager.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/mapper/KidDtoMapper.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/personality/PersonalityManager.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/personality/PersonalityQuestionManager.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/util/MBTI.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/util/MBTIUtil.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/book/BookRepository.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/book/BooksCharacteristicRepository.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/personality/PersonalityQuestionRepository.java
src/main/java/com/ureca/idle/idlejpa/book/Book.java
src/main/java/com/ureca/idle/idlejpa/kid/Kid.java
src/main/resources/application.yml
src/test/java/com/ureca/idle/idleapi/idleoriginapi/implementation/BookManagerTest.java

> ## 📝 관련 이슈
---
- [resolves]: [ID-48 랜덤 MBTI Generator 구현](https://trello.com/c/kZRhml1z/48-id-48-%EB%9E%9C%EB%8D%A4-mbti-generator-%EA%B5%AC%ED%98%84)
> ## 💻 작업 내용
- MBTI 관련 Util 안에 랜덤 MBTI 생성 기능을 구현해놨습니다.
- 해당 기능을 책, 자녀 생성 로직에 추가해줬습니다.
---
> ## 🙇 특이 사항
- 
---
- 
---

[ID-48] 랜덤 MBTI Generator 구현

---

src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/preference/PreferenceManagingService.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/preference/PreferenceManagingUseCase.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/preference/PreferenceManager.java
src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/book/BookPreferenceRepository.java

> ## 📝 관련 이슈
---
- [resolves]: [ [ID-47] 도서 평가 (좋아요/싫어요) api 일부](https://trello.com/c/60dtDdah/47-id-47-%EB%8F%84%EC%84%9C%ED%8F%89%EA%B0%80-%EC%A2%8B%EC%95%84%EC%9A%94-%EC%8B%AB%EC%96%B4%EC%9A%94-api)
> ## 💻 작업 내용
- 도서 평가 좋아요 싫어요 기능 구현
- 좋아요 싫어요 완성
- 다음에 추가할 내용: 좋아요 싫어요를 kid 성향에 반영
---

[ID-47]  (좋아요/싫어요) api 일부

---

src/main/java/com/ureca/idle/originapi/business/bookPreference/BookPreferenceManagingService.java
src/main/java/com/ureca/idle/originapi/implementation/bookPreference/BookPreferenceManager.java
src/main/java/com/ureca/idle/originapi/implementation/kid/KidManager.java

> ## 📝 관련 이슈
---
- [resolves]: [[ID-58] 책 평가 kid 성향 반영 리팩토링](https://trello.com/c/vTETRhZ2/58-id-58-%EC%B1%85-%ED%8F%89%EA%B0%80-kid-%EC%84%B1%ED%96%A5-%EB%B0%98%EC%98%81-%EB%A6%AC%ED%8C%A9)
> ## 💻 작업 내용
- 좋아요 눌렀다가 싫어요 눌렀을 때 아이 성향에 반영하는 부분 가독성 향상
---

[ID-58] 책 평가 kid 성향 반영 리팩토링

---

src/main/java/com/ureca/idle/jpa/kid/Kid.java

> ## 📝 관련 이슈
---
- [resolves]: [엔티티 오류 수정](https://trello.com/c/c586cY9C/64-id-64-%EC%97%94%ED%8B%B0%ED%8B%B0-%EC%98%A4%EB%A5%98-%EC%88%98%EC%A0%95) #ID-64
> ## 💻 작업 내용
- Kid와 User의 관계 ManyToOne으로 수정
---
> ## 🙇 특이 사항
- 
---
- 
---

[ID-64] 엔티티 오류 수정

---

src/main/java/com/ureca/idle/originapi/presentation/controller/personalityQuestion/PersonalityQuestionController.java

> ## 📝 관련 이슈
---
- [resolves]: [ID-72 성향 테스트용 질문 API 이름 수정](https://trello.com/c/kXKpZno0/72-id-72-%EC%84%B1%ED%96%A5-%ED%85%8C%EC%8A%A4%ED%8A%B8%EC%9A%A9-%EC%A7%88%EB%AC%B8-api-%EC%9D%B4%EB%A6%84-%EC%88%98%EC%A0%95)
> ## 💻 작업 내용
- 성향 테스트용 질문 API path 수정
---
> ## 🙇 특이 사항
- 
---
- 
---

[ID-72] 성향 테스트용 질문 API path 수정

---

src/main/java/com/ureca/idle/originapi/presentation/controller/auth/AuthController.java
src/main/java/com/ureca/idle/originapi/presentation/controller/book/BookManagingController.java
src/main/java/com/ureca/idle/originapi/presentation/controller/kid/KidManagingController.java
src/main/java/com/ureca/idle/originapi/presentation/controller/personalityQuestion/PersonalityQuestionController.java

> ## 📝 관련 이슈
---
- [resolves]: [[ID-74] 프론트 서버 연결 설정 추가](https://trello.com/c/1vIjC32u/74-id-74-%ED%94%84%EB%A1%A0%ED%8A%B8-%EC%84%9C%EB%B2%84-%EC%97%B0%EA%B2%B0-%EC%84%A4%EC%A0%95-%EC%B6%94%EA%B0%80)
> ## 💻 작업 내용
- 지금은 localhost로 들어가있지만 실제 배포시에는 프론트 서버로 바꿀 예정입니다. 개발을 위해서 우선 어노테이션 추가했습니다.
---

[ID-74] 프론트 서버 연결 설정 추가

---

src/main/java/com/ureca/idle/originapi/business/kid/dto/GetKidsProfileResp.java
src/main/java/com/ureca/idle/originapi/implementation/mapper/KidDtoMapper.java

> ## 📝 관련 이슈
---
- [resolves]: [ID-80 내 자녀 프로필 가져오기 할 때 Gender 추가](https://trello.com/c/LqXWuKif/80-id-%EB%82%B4-%EC%9E%90%EB%85%80-%ED%94%84%EB%A1%9C%ED%95%84-%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0-%ED%95%A0-%EB%95%8C-gender-%EC%B6%94%EA%B0%80)
> ## 💻 작업 내용
- 
---
> ## 🙇 특이 사항
- 
---
- 
---

[ID-80] 내 자녀 프로필 가져오기 할 때 Gender 추가

---

.gitignore
src/main/java/com/ureca/idle/aiclient/implementation/LgAiManager.java
src/main/java/com/ureca/idle/jpa/book/Book.java
src/main/java/com/ureca/idle/originapi/business/book/BookManagingService.java
src/main/java/com/ureca/idle/originapi/business/book/dto/AddBookResp.java
src/main/java/com/ureca/idle/originapi/implementation/kid/KidManager.java
src/main/java/com/ureca/idle/originapi/implementation/mapper/BookDtoMapper.java
src/main/java/com/ureca/idle/originapi/persistence/kid/KidsPersonalityChangeHistoryRepository.java
src/main/java/com/ureca/idle/originapi/presentation/controller/auth/AuthController.java
src/main/java/com/ureca/idle/originapi/presentation/controller/book/BookManagingController.java
src/main/java/com/ureca/idle/originapi/presentation/controller/kid/KidManagingController.java
src/main/java/com/ureca/idle/originapi/presentation/controller/personalityQuestion/PersonalityQuestionController.java
src/main/resources/application.yml

> ## 📝 관련 이슈
---
- [resolves]: [[ID-41] AI API 디테일 보수](https://trello.com/c/zK0GYvRa/41-id-41-ai-api-%EB%94%94%ED%85%8C%EC%9D%BC-%EB%B3%B4%EC%88%98)
> ## 💻 작업 내용
- AI 답변 정제 형식 변경
- AI 성능 향상 (50초 -> 2초)
- AI IP 관련 설정 추가
---

[ID-41] AI API 디테일 보수

---

src/main/java/com/ureca/idle/aiclient/implementation/LgAiManager.java
src/main/java/com/ureca/idle/jpa/book/Book.java
src/main/java/com/ureca/idle/originapi/implementation/book/BookManager.java

> ## 📝 관련 이슈
---
- [resolves]: [[ID-87] add-book 프론트 관련 백엔드 수정](https://trello.com/c/GdnCWvCb/87-id-87-add-book-%ED%94%84%EB%A1%A0%ED%8A%B8-%EA%B4%80%EB%A0%A8-%EB%B0%B1%EC%97%94%EB%93%9C-%EC%88%98%EC%A0%95)
> ## 💻 작업 내용
- 필요없는 자료 뺐습니다
---

[ID-87] add-book 프론트 관련 백엔드 수정

---

src/main/java/com/ureca/idle/fcfsproducer/caller/CallSubmissionProducerReq.java
src/main/java/com/ureca/idle/fcfsproducer/caller/SubmissionProducerWebRequestCaller.java
src/main/java/com/ureca/idle/fcfsproducer/event/Submission.java
src/main/java/com/ureca/idle/jpa/submission/CurrentRoundSubmission.java
src/main/java/com/ureca/idle/jpa/submission/PreviousRoundSubmission.java
src/main/java/com/ureca/idle/originapi/business/submission/dto/GetSubmissionResultResp.java
src/main/java/com/ureca/idle/originapi/implementation/submission/SubmissionManager.java
src/main/java/com/ureca/idle/originapi/persistence/submission/PreviousRoundSubmissionRepository.java

> ## 📝 관련 이슈
---
- [resolves]: [[ID-90] time stamp 타입 변경](https://trello.com/c/zlGiGgrB/90-id-time-stamp-%ED%83%80%EC%9E%85-%EB%B3%80%EA%B2%BD)
> ## 💻 작업 내용
- String to LocalDateTime
---

[ID-90] time stamp 타입 변경

---

.gitignore
Dockerfile
src/main/resources/properties/jpa.yml
src/main/resources/properties/mysql.yml
src/main/resources/properties/redis.yml

> ## 📝 관련 이슈
---
- [resolves]: [ID-94 idle-server CD](https://trello.com/c/TDAYYiHz/94-id-94-idle-server-cd)
> ## 💻 작업 내용
- 
---
> ## 🙇 특이 사항
- 
---
- 
---

[ID-94] idle-server CD

---

src/main/java/com/ureca/idle/originapi/presentation/controller/book/BookManagingController.java
src/main/java/com/ureca/idle/originapi/presentation/controller/kid/KidManagingController.java
src/main/java/com/ureca/idle/originapi/presentation/controller/personalityQuestion/PersonalityQuestionController.java

> ## 📝 관련 이슈
---
- [resolves]: [[ID-95] 백엔드에 프론트 서버 IP 수정](https://trello.com/c/9uq2PJ4d/95-%ED%95%98%EC%95%84)
> ## 💻 작업 내용
- 백엔드에 프론트 서버 IP 수정
---

[ID-95] 백엔드에 프론트 서버 IP 수정
